# Explore MODIS dates

This notebook explores the dates used for the MODIS periods. A key finding is that not all dates are 8 days apart - the 8-day periods do not cross over years, and so a new period begins no the first of every year. This needs to be considered for creation of the future 8-day periods for aggregating WRF data.

In [1]:
import datetime, glob, os
import pandas as pd
import numpy as np

mod_dir = os.getenv("MODIS_DIR")
fps = sorted(glob.glob(os.path.join(mod_dir, "MOD11A2", "*h11*.hdf")))
jdates = [fp.split(".")[-5][1:] for fp in fps]
modis_dates = [
    datetime.datetime.strptime(jdate, "%Y%j").strftime('%Y-%m-%d') 
    for jdate in jdates
]

Show the unique numbers of differences between starting dates:

In [2]:
mod_diffs = (pd.to_datetime(modis_dates[1:]) - pd.to_datetime(modis_dates[:-1])).days
np.unique(mod_diffs)

array([ 5,  6,  8, 16])

Some indices where differences are 5 and 6 days, respectively:

In [3]:
print(np.where(mod_diffs == 5))
print(np.where(mod_diffs == 6))

(array([ 84, 130, 176, 268, 314, 360, 452, 498, 544, 636, 682, 728, 820,
       866, 912]),)
(array([ 39, 222, 406, 590, 774]),)


Examine some starting dates for periods having fewer than 8 days:

In [4]:
print(modis_dates[84:86])
print(modis_dates[130:132])
print(modis_dates[176:178])
print(modis_dates[39:41])
print(modis_dates[222:224])
print(modis_dates[406:408])

['2001-12-27', '2002-01-01']
['2002-12-27', '2003-01-01']
['2003-12-27', '2004-01-01']
['2000-12-26', '2001-01-01']
['2004-12-26', '2005-01-01']
['2008-12-26', '2009-01-01']


So, [this page](https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/MOD11B2/), although for MOD11B2, suggests that a new 8-day period begins on the first of every year. 